services:
  booru:
    build: .
    container_name: booru
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://booru:booru@postgres:5432/booru
      THUMBNAIL_PATH: /thumbnails
    volumes:
      - "Z:/Hydrus:/hydrus:ro"
      - thumbnails:/thumbnails

    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:18-alpine
    container_name: booru-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: booru
      POSTGRES_PASSWORD: booru
      POSTGRES_DB: booru
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U booru -d booru"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  thumbnails:
